### ISSUE TITLE
No auth

### ISSUE THREAD

**Issue by drewblaisdell** [drewblaisdell/monitor.io#1]
There is currently no way to prevent anyone from port scanning and accessing monitor.io. Before monitor.io is production-ready, it needs to be secured over SSL and require proper user credentials.

**Comment by FGRibreau** [comment]
:+1:

**Comment by dasilvacontin** [comment]
:+1:

**Comment by drewblaisdell** [comment]
Using localOnly mode and connecting via telnet on a remote box solves this problem: https://github.com/drewblaisdell/monitor.io/commit/1d8138920595076eeecd92e8b619d92ff3163bbd
